### ISSUE TITLE
Error in null: Ambiguous truth value of a Series

### ISSUE THREAD

**Issue by MengChenC** [cleanlab/cleanlab#1043]
I encountered the error:
> Error in null: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

when running the following code snippet:
```
columns = [...] # columns that are independent variables.  
model = LogisticRegression()
pred_probs = cross_val_predict(
    estimator=model, X=data[columns], y=data["y"], cv=5, method="predict_proba"
)
lab = Datalab(data[columns], label_name="y")
lab.find_issues(pred_probs=pred_probs, features=data[columns])
```

I trace back to a potential bug in line 89 of the script:
[null_issue_manager](https://github.com/cleanlab/cleanlab/blob/master/cleanlab/datalab/internal/issue_manager/null.py)
where `if null_tracker.any():` will cause the error.

`null_tracker` generates a dataframe of booleans, and `null_tracker.any()` condenses the result into a Series of booleans of each column:

null_tracker example
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; B &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; C   &nbsp;&nbsp;&nbsp;...&nbsp;&nbsp;&nbsp;   Z
   1 &nbsp; True &nbsp;&nbsp; False &nbsp; False &nbsp;&nbsp;&nbsp; True
   2 &nbsp; False &nbsp; False &nbsp; False &nbsp;&nbsp;&nbsp; False
   3 &nbsp; False &nbsp; True &nbsp;&nbsp; False &nbsp;&nbsp;&nbsp; False
   ...
   n &nbsp; False &nbsp; False &nbsp; False &nbsp;&nbsp;&nbsp; False
n rows x 26 columns

null_tracker.any() example:
>A &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; True
B &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; True
C &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; False
...
Z &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; True
Length: 26, dtype: bool

so when you call the `if` condition on `null_tracker.any()`, the truth value is ambiguous and will incur the error.
An easy fix will be using `if sum(null_tracker.any()):` to replace the original code.

The python version is 3.9.1, and the cleanlab version is 2.6.1

**Comment by elisno** [comment]
Thank you for the report @MengChenC 

You're trying to demonstrate this kind of workflow (your `pred_probs` will not be passed to the null issue-check method, so we'll omit that in the example, we can also skip the `labels` for demonstration purposes).

```python

### CREATE DATASET

import numpy as np
import pandas as pd

dataset = {
    "features": np.array([[1, 2, np.nan], [4, np.nan, 6], [np.nan, 8, 9]]),
}

feature_columns = [f"x{i+1}" for i in range(len(dataset["features"][0]))]
df = pd.DataFrame(dataset["features"], columns=feature_columns),


print(df)
#      x1   x2   x3
#  0  1.0  2.0  NaN
#  1  4.0  NaN  6.0
#  2  NaN  8.0  9.0


### RUN DATALAB

from cleanlab import Datalab
lab = Datalab(data=df)

lab.find_issues(features=df, issue_types={"null": {}})
# Finding null issues ...
# Error in null: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
# Failed to check for these issue types: [NullIssueManager]
# 
# Audit complete. 0 issues found in the dataset.
```

You're passing in `features` as a DataFrame instead of an array, which is the recommended approach and primary expected input format to `Datalab.find_issues`. ( See [relevant API reference](https://docs.cleanlab.ai/stable/cleanlab/datalab/datalab.html#cleanlab.datalab.datalab.Datalab.find_issues))

The best approach is to run

```python
lab.find_issues(features=df.to_numpy(), issue_types={"null": {}})
```


---

## How this will be addressed.

We can apply the changes you suggest about the null_tracker to explicitly look at every element in the null_tracker.
Thank you for the suggestion! 👍 

But we'll turn internally turn `features: pd.DataFrame` into a numpy array while performing the null issue check. We'll still make the `np.any` check more explicit.
See the ongoing PR #1045.

**Comment by elisno** [comment]
Hey @MengChenC 

The changes you suggested have made its way to a new patch release.

Try running this on cleanlab v2.6.2.

```
# Upgrade to 
pip install -U cleanlab
```

**Comment by MengChenC** [comment]
Hi @elisno 

Thank you for making the update nimbly.

I can confirm this is now working for the same dataset 🎉
