### ISSUE TITLE
Why Pruning and not fixing labels error?

### ISSUE THREAD

**Issue by filippoBUO** [cleanlab/cleanlab#112]
Hi 

I don't get why you say this "CL is based on the principles of pruning noisy data (as opposed to fixing label errors...)..."

I mean If for example I'm in binary classification and you give me the indices of noisy labels I will simply change those labels to the other class rather than throw them away. Or in the case of multiclass I will simply put the argmax of pyx as the clean label from compute_pyx.

What am I missing?

Thank you! (I hope I'll get an answer because it seems that here no one answers)

**Comment by cgnorthcutt** [comment]
Hi @filippoBUO 

You can try using the argmax predictions as new labels, but there are several reasons why this is probably a bad idea. Here are three:

1. `cleanlab` isn't perfect. There are cases when it exactly finds label errors and you can learn about those in the [confident learning paper](https://arxiv.org/abs/1911.00068), but for most real-world models, the predicted probabilities tend to be highly imperfect/error-prone, resulting in some mistakes within the set of found label issues.
2. In the binary case, you might end up flipping the labels for some examples that are correctly labeled!! Even worse, you might do this every time you have a certain type of example (due to your model doing poorly on those types of examples) creating a systematic error in all data of a certain kind (which result in a further biased model on final training).
3. For multi-class case, again label error finding isn't perfect, but also unless you have a perfect model with 100% generalization test accuracy, the predicted (argmax) labels will also introduce errors if you use them as new labels. So you introduce to sources of errors (relabeling with the wrong new label and also potentially relabeling examples that aren't actually errors). Overall, you may end up with fewer errors than you started with, but the problem is that your model's predictions will now re-label in a **biased** way. It might relabel all dog errors as wolf because it gets confused on those two classes, so like in the binary case, when you re-train your model on the new data.

Note that using argmax predictions during training in conjunction with good labels has been effective in certain cases (e.g. pseudo labeling), but this requires training in a particular order and combination of actual labels and predictions and can lead to weird self-reinforcing pitfalls like those mentined above.
