### ISSUE TITLE
an extension of cleanlab for regression tasks

### ISSUE THREAD

**Issue by dzankov** [cleanlab/cleanlab#17]
Will there be an extension of the algorithm for regression tasks?

**Comment by cgnorthcutt** [comment]
Eventually :)

**Comment by cgnorthcutt** [comment]
Regression support is now officially in expected future support. You can see what features we plan to support in the future here: https://github.com/cgnorthcutt/cleanlab/blob/master/cleanlab/version.py

For researchers, scientists, programmers, and engineers working with label noise, uncertainty, and learning with noisy labels -- submissions and pull requests are encouraged. If you have ideas and would like to contribute, let me know.

**Comment by kexul** [comment]
@cgnorthcutt Is there a timeline? Thanks so much for your great job!

**Comment by TKassis** [comment]
Looking forward to extending this framework to regression labels!

**Comment by kennysong** [comment]
@cgnorthcutt Sorry to revive an old issue, but it looks like Cleanlab still doesn't directly support regression in 2.0.0.

Is the recommended way for detecting numeric label errors bucketizing into multi-class classification?

**Comment by cgnorthcutt** [comment]
Hi @kennysong . I planned to support regression two years ago but then needed to finish my PhD and started a couple companies. Since then, cleanlab has grown considerably and it's back on the road map for fall 2022. 

For now if you need to get started, bucketing via discretization is the right approach. 

If you work on this yourself before the fall, definitely submit a PR in the experimental/ module! Then we can help you directly in your code and add commits if you have questions. Also it's a great way to contribute to Cleanlab! Also this way we can test your approach on our benchmarks.
