### ISSUE TITLE
get_confident_thresholds fails with numpy error on multi-label problem, what are the limitations of multi-label ?

### ISSUE THREAD

**Issue by suneeta-mall** [cleanlab/cleanlab#263]
Thanks a lot for your work on clean lab and for pulling all the theories together to build nice general framework for error management.  

I noticed that in your paper [here](https://arxiv.org/abs/2103.14749) & [here](https://arxiv.org/abs/1911.00068) you don't talk a whole a lot about multi-label support but your implementation (cleanlab) supports multi-label.  It's great that the support is there. However, fundamentally I am not sure how you represent multi-label as a pair-wise joint distribution and still consider off-diagonal elements in the joint matrix as noise?  Could you please provide some detail and thinking behind multi-level support?

For records, I have used version ` '2.0.0'` of cleanlab.
More than a theoretical question, I have run cleanlab over a usecase I have with multi-label and I can get the label noise and self-confidence metrics working, like following:
```
In [38]:     confident_joint_matrix = cleanlab.count.compute_confident_joint(
    ...:        truth
    ...:         predictions,
    ...:         multi_label=True,
    ...:     )
```
The result I get here is as expected the following (I have 6 class output, lets say my classes are  `['airplane', 'airport', 'buildings', 'cars', 'runway', 'trees']`). What I am unclear on is how do interpret this? I can have airplane and airport both a valid class so essentially means off-diagonal are no longer noise.
```
In [39]: confident_joint_matrix
Out[39]:
array([[119,  26,  36,  18,  29,   8],
       [ 28,  51,  60,   6,  59,  29],
       [ 24,  53,  63,   8,  64,  31],
       [ 12,   2,   6,   6,   0,   0],
       [  6,  50,  61,   0,  72,  34],
       [  2,  26,  31,   0,  34,  24]])
```

Also, another issue I ran into when I looked at estimating the threshold,  details of this is as following:
```
/core/_methods.py:189: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
Out[40]: array([nan, nan, nan, nan, nan, nan], dtype=float32)
```
Maybe this error is more helpful:
```
   1091 def get_confident_thresholds(labels: np.array, pred_probs: np.array) -> np.array:
   1092     """Returns expected (average) "self-confidence" for each class.
   1093 
   1094     The confident class threshold for a class j is the expected (average) "self-confidence" for class j.
   (...)
   1114       An array of shape ``(K,)``.
   1115     """
   1116     confident_thresholds = np.array(
-> 1117         [np.mean(pred_probs[:, k][labels == k]) for k in range(pred_probs.shape[1])]
   1118     )
   1119     return confident_thresholds

IndexError: too many indices for tensor of dimension 1

```

This is the call that I used:
```
In [40]:     cleanlab.count.get_confident_thresholds(
    ...:         truth,
    ...:         predictions,
    ...:     )
```

My truth is not one hot encoded but is correctly presented as list of list as indicated here 
https://github.com/cleanlab/cleanlab/issues/55#issuecomment-799057008

More info can be found here https://github.com/suneeta-mall/label_noise/blob/master/label_noise_notebook.ipynb

Also, did a post on your cool work recently https://suneeta-mall.github.io/2022/05/16/confident-learning-clean-data.html, would welcome feedback and suggestions if you have any!

**Comment by cgnorthcutt** [comment]
Hi @suneeta-mall , great questions and fantastic issue reporting. Really appreciate this! Our multi_label support is a bit experimental currently - indeed you found a bug! (currently being fixed in https://github.com/cleanlab/cleanlab/pull/264  :)

To answer your questions on the current implementation:

> What I am unclear on is how do interpret this? I can have airplane and airport both a valid class so essentially means off-diagonal are no longer noise.

The off-diagonals represent the unnormalized joint probability of a label co-occurring in a datapoint (not necessarily a label issue). So, a 10 (let's say out of 1000) for entry (noisy label airplane, true label car) would say that the label "airplane" is likely to occur in an image that contains a "car" in your dataset about 1% of the time, regardless of how often there is actually an airplane in those images including cars. Does that make sense? (If you can think of alternative representations that may be more useful, would love your input here!)

> the nan bug you're facing

Should be fixed in PR https://github.com/cleanlab/cleanlab/pull/264 -- we'll review over the next few days and get this fix introduced.

**Comment by suneeta-mall** [comment]
In a multi-class dataset, the classes are mutually exclusive by definitions. In that case, it is fair to say we can build pair-wise joint distribution. 
IMO, the multi-label scenario is very different from a multi-class because in multi-label the classes are independent. If we go with the assumption that `Label noise is class-conditional, depending only on the latent true class, not the data` or context! then then pair-wise joint distribution only gives a partial picture IMO. In multi-class, it is fair because the classes are dependent i.e. if one is present then the other has to be absent. Do you disagree? 

My intuition says the right approach to model joint distribution for multi-label is not pairwise but all-classes. That is the matrix should represent every possible combination (a joint distribution of all classes) of outcomes, which is then used to estimate the rate of errors. This is obviously extremely space complex (and if I am understanding correctly, will lead to a sparse matrix too) so needs more thinking. I will revert back if I get better ideas.
As you can see, my biggest challenge lies in accepting pair-wise as a fair choice to model multi-label.

**Comment by cgnorthcutt** [comment]
Great points. We'll need to avoid the exponential space representation, but I like the idea of modeling general tuples of overlap. Please do follow up if you think of an efficient representation (my guess would be a tree structure instead of a matrix).

I think the current solution using the pairwise joint distribution works well as long as you recognize it's interpretation is different. It's not the mutual error, but the probability of one class occurring within a data point that contains another class. For that interpretation, the current representation is useful for measuring class overlap, but not label error directly.

**Comment by cgnorthcutt** [comment]
https://github.com/cleanlab/cleanlab/pull/264 has been merged!

Please let us know if you're still encountering any issues here :) Thanks again for bringing this to our attention.

**Comment by aditya1503** [comment]
Hi @suneeta-mall 
In cleanlab v2.2, we did a major overhaul of the functionality for multi-label classification. All of these issues should now be resolved, and cleanlab's new label error detection capabilities for multi-label classification are much more powerful and easy to use!

Get started here: https://docs.cleanlab.ai/stable/tutorials/multilabel_classification.html
Here's a snippet of your code working for getting confidence thresholds: 
 
![image](https://user-images.githubusercontent.com/9433028/209271007-22bcb9d1-006e-45b0-a104-7fccc5c7b954.png)

You can refer to documentation  [cleanlab.count.get_confident_thresholds][https://github.com/cleanlab/cleanlab/blob/75bac0a28438fc606c7caff52d518774b33a5101/cleanlab/count.py#L1357] for the expected labels format when multi_label=True.


And definitely please open a new issue (stating which cleanlab version you are using) if you still encounter any problems using cleanlab for multi-label datasets.

**Comment by suneeta-mall** [comment]
Good stuff @aditya1503 🚀 ! I will check it out in the coming days!
