### ISSUE TITLE
TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### ISSUE THREAD

**Issue by yrqUni** [cleanlab/cleanlab#274]
When I use the **from cleanlab.filter import find_label_issues**
I get the following  ERROR **TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''**

**Comment by cgnorthcutt** [comment]
Hi @yrqUni , thanks for sharing. To debug, we need more info. Can you share a minimal viable example to reproduce the error? If that's too tricky, please share everything you can think of about your dataset... How many classes, what type of data, single label or multi label, how many examples, etc.

Also please share the exact function call you used with the parameters so we can take a look at your issue.

Thanks!

**Comment by anishathalye** [comment]
Sharing a full stack trace (rather than just the exception) would also be helpful.

**Comment by calebchiam** [comment]
This error came up in Cleanlab Studio as well. The problem seems to be that we passed a pred probs numpy array to `find_label_issues`, where the values were strings instead of floats. 

This was the method call:
```
label_issues_indices = cleanlab.filter.find_label_issues(
        labels=df[label_column],
        pred_probs=pred_probs,
        filter_by="prune_by_noise_rate",
        return_indices_ranked_by="normalized_margin",
    )
```

Oddly, I could not reproduce the exact error locally, it instead results in `TypeError: unsupported operand type(s) for /: 'str' and 'int'`. This may be due to differences in `numpy` versions perhaps, but I didn't investigate further.

This perhaps motivates adding a check to the `dtype` of numpy arrays that are passed to `find_label_issues` so that we produce a more interpretable error message.

**Comment by jwmueller** [comment]
The latest developer version now has a check to ensure string numpy arrays are not being passed in. If you still see this issue come up using it, then feel free to reopen this issue!
