### ISSUE TITLE
Is it possible to use CleanLab for more complex learning tasks than regression or classification?

### ISSUE THREAD

**Issue by AndreaPi** [cleanlab/cleanlab#586]
I usally deal with semantic segmentation and instance segmentation (structured prediction), instead of classification. Can CleanLab help with that?

**Comment by jwmueller** [comment]
We don't have dedicated functionality for segmentation & object detection tasks yet, but our team is actively working on these!  Our roadmap is publicly available here:  https://github.com/orgs/cleanlab/projects/2/views/1

I'll ping you here once we have merged the code in.

For now, here's one hacky way you can try using cleanlab for semantic segmentation: 
1. Train your segmentation model M in the usual way.  To get the best results with cleanlab, use [cross-validation to produce out-of-sample predicted probabilities](https://docs.cleanlab.ai/stable/tutorials/pred_probs_cross_val.html) for every image in your entire dataset.
2. You can then try to apply cleanlab's dedicated [token classification](https://docs.cleanlab.ai/stable/tutorials/token_classification.html) functionality, but will first need to remap your predicted class probabilities and labels to match the input format demonstrated in cleanlab's token-classification tutorial.  Here you can treat each image as a "sentence" and each pixel as a "token" (simply pretending the pixels are a sequence even though they are not).  Once you have suitably reformatted your segmentation `labels` and `pred_probs` for token-classification, then you can call [cleanlab.token_classification.rank.get_label_quality_scores()](https://docs.cleanlab.ai/stable/cleanlab/token_classification/rank.html#cleanlab.token_classification.rank.get_label_quality_scores).  This will give you one score per image corresponding to the overall quality of the segmentation annotations for this image (lower scores are images more likely to have some sort of label error).

If you have high-res images and too many pixels per image for this to run quickly, then you can try treating as tokens each sub-region of the image (say 8x8 grid of pixels) instead of each pixel. To apply cleanlab to sub-region tokens, you will need to pool the given `labels` and `pred_probs` from your model across pixels in each sub-region to form a single class label and single predicted-class-probability-vector for each sub-region.

**Comment by AndreaPi** [comment]
Very interesting, thanks!

1. When you ask to compute the predicted probabilities, you mean the probability of each class for each pixel, right? Thus, a `numpy` array (I guess) of size HxWxK, where H=height; W=width; K=# of classes - 1 (I included a `background` class). Correct?
2. Sub-region tokens. How can I generate them? If I understand correctly, I should go from a 8x8xK array, to a 1x1xK (the class label is then easy - just choose the class corresponding to the max probability). You're suggesting to perform max-pooling or mean-pooling over the probabilities, for each class separately. Right?

**Comment by jwmueller** [comment]
**Re (1) pred_probs formatting:**

> you mean the probability of each class for each pixel, right? 

Yes exactly, the raw numpy array is of size HxWxK containing the probability of each class for each pixel. To feed this into cleanlab.token_classification, you just need to flatten the H x W axes, since tokens in a sentence have no spatial structure (FYI ordering that the tokens appear does not matter to cleanlab, which assumes the pred_probs already capture the relevant contextual info for each token). And including a `background` class is always a good idea!

**Re (2) sub-region tokens:**

> I should go from a 8x8xK array, to a 1x1xK (the class label is then easy - just choose the class corresponding to the max probability). You're suggesting to perform max-pooling or mean-pooling over the probabilities, for each class separately. Right?

Yep you mostly got it! The given class label for one entire sub-region (aka one token) could just be chosen via majority-voting of the class labels for each pixel within the sub-region. Or you can define fancier (non-grid) sub-regions that only contain pixels all labeled as the same class. To get pred_probs for the sub-region (one K-dimensional vector for each region), exactly I suggest either performing mean (or max) pooling over the probabilities for each class over all pixels within the sub-region. 

Which pooling method produces the most representative pred_prob for the entire region is what we're actively researching/benchmarking, I'll let you know what we find!

**Comment by jwmueller** [comment]
Cleanlab can now be used for:
segmentation:  https://docs.cleanlab.ai/master/tutorials/segmentation.html
and object detection:  https://docs.cleanlab.ai/master/tutorials/segmentation.html
