### ISSUE TITLE
After filtering with confident learning, remove issues where given label == argmax model prediction - Why?

### ISSUE THREAD

**Issue by maraaos** [cleanlab/cleanlab#722]
When using the function find_label_issues in cleanlab.filter, after applying one of the five main filtering approaches ("predicted_neq_given", "prune_by_class", "prune_by_noise_rate", "both", "confident_learning"), the following code is implemented before returning the label issues mask:

if filter_by not in ["low_self_confidence", "low_normalized_margin"]:
        # Remove label issues if given label == model prediction if issues haven't been removed yet
        pred = pred_probs.argmax(axis=1)
        for i, pred_label in enumerate(pred):
            if pred_label == labels[i]:
                label_issues_mask[i] = False

Why is this implemented? 

For example, if I am using "confident_learning", by removing label issues if the given label equals the argmax model prediction, all issues are removed, which are not in the filtering approach "predicted_neq_given" (which is equal to using the argmax or the confusion matrix). Thus, all issues found when using confident learning are also in the confusion matrix, but not all issues found when using the confusion matrix are in the confident joint. In other words, filtering by confident learning is dependent from the argmax confusion matrix.
Neither can I find anything about this in the paper, nor do I see the reason why this is done. Does it simply give better results?

I would love to here why this is implemented. Thanks in advance!

**Comment by cgnorthcutt** [comment]
Hi @maraaos , thanks for the question. the idea is if the model is most confident in the given label among all possible classes, in some cases we've seen better results by not marking that example as a label issue empirically.

However, its a good point because any example where this occurs means that it's argmax == given label, but also it has very low probability(given label), which means its distribution of probabilities likely has high entropy (more uniform) and so the example may indeed still be likely to be an error but in the from of an outlier (which is indirectly also a label error since the label is incorrect for outliers, but its also a data error since the data point itself doesn't belong in distribution). I think this requires further inspection, benchmarking and the implications differ slightly for each method, so we'll take a look into it.
