### ISSUE TITLE
[enhancement] DataLab for regression

### ISSUE THREAD

**Issue by mglowacki100** [cleanlab/cleanlab#765]
Initiated by discussion https://github.com/cleanlab/cleanlab/discussions/137 @jwmueller 
I think it'd be nice to have `DataLab` functionality also for regression task when it will be oficially released.
I've looked at codebase and as far I see, `DataLab` is closely coupled with classification (e.g. method signature `find_issues(features=feature_embeddings, pred_probs=pred_probs)`, see `pred_probs`), so at the moment I'm not sure if this class could be easily and properly extended.
I've also noticed that besides `regression` task that is a little odd-ball, there are `object detection`, `segmentation`, `token_classification` and I don't know if `DataLab` supports them already? If no, maybe a better approach is to provide separate `DataLabs` for every task (with reusage of factory registration mechanism)?
Please let me know, what you think about it?

**Comment by jwmueller** [comment]
Thanks for starting off the discussion!  CCing @elisno whose thoughts I'm curious to hear.

**Comment by elisno** [comment]
Hi @mglowacki100, thank you for your suggestion. This is a crucial topic that we want to address.

I agree that `Datalab`'s method signatures are currently more oriented towards classification tasks. As we continue to add features that cater to various tasks, it's essential to consider how `Datalab` can be adapted to support these.

Starting with regression tasks is a good idea, but we should also approach this to handle future tasks.

However, instead of creating separate `Datalab` classes for each task type, we should introduce an argument to the `Datalab` constructor. This way, most of the work can be managed by a new issue mnager, keeping things clean and efficient.


---

To set the wheels in motion, I've opened [this issue](https://github.com/cleanlab/cleanlab/issues/774). It outlines the main steps required to kick-start regression support in `Datalab`.

How would you feel about contributing to this next step, @mglowacki100?

**Comment by mglowacki100** [comment]
@elisno thanks for action plan! I'd work on this in next couple of days and let you know if I encounter any blockers or difficulties.
Btw. have you consider moving `classification.py` into new folder `classification` and renaming it into `learn.py` to make it more consistent with regression and other tasks? Or is it make on purpose and other tasks use "classification", as I didn't find for them `CleanLearnig` class?

**Comment by elisno** [comment]
>Btw. have you consider moving `classification.py` into new folder `classification` and renaming it into `learn.py` to make it more consistent with regression and other tasks? Or is it make on purpose and other tasks use "classification", as I didn't find for them `CleanLearnig` class?

Good question! For now, let's just work on adding regression before thinking about restructuring the modules.

**Comment by jwmueller** [comment]
@mglowacki100 yes the long-term plan is to move everything classification-related into a `classification/` folder, but that will not happen anytime soon (as it is a significant chunk of the current package)

**Comment by mglowacki100** [comment]
@jwmueller Sure, besides code changes it would requires changes in examples, docs and tests.

**Comment by mglowacki100** [comment]
@jwmueller Thanks! It's been a great team effort. I appreciate the opportunity to contribute.
Best regards,
Marek
