### ISSUE TITLE
add a unit test that `datalab.issues` solely contains numeric and boolean values

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#937]
Can go in this file:

https://github.com/cleanlab/cleanlab/blob/master/tests/datalab/test_datalab.py

Also add a second unit test that `datalab.issue_summary` solely contains numeric values.

**Comment by sanjanag** [comment]
https://github.com/cleanlab/cleanlab/blob/master/tests/datalab/test_cleanvision_integration.py should also contain a test testing there are solely numeric values in datalab.issues. Currently, it is broken because `score` column does not extend to cleanvision right now.
<img width="959" alt="Screenshot 2024-02-06 at 3 38 40 PM" src="https://github.com/cleanlab/cleanlab/assets/7639432/bb9a85e2-44a3-47cb-8a45-2922d0d7f59e">
