### ISSUE TITLE
Obtaining the Ambiguity score?

### ISSUE THREAD

**Issue by tqdo** [cleanlab/cleanlab#939]
I am using the trial of Cleanlab Studio and I notice that every record has an "Ambiguity Score" but I could not find it anywhere in the [doc](https://docs.cleanlab.ai/stable/index.html). Is it a feature that is only available for Cleanlab Studio and not published in this repo? Thanks

**Comment by jwmueller** [comment]
**Major difference to note:**  Cleanlab Studio does all of the ML for you automatically, whereas using this library you need to train your own effective ML model. 

Beyond that, once you have `pred_probs` from your ML model, the closest thing you can do in this library that will resemble the Ambiguity Score from Cleanlab Studio is as follows:

```
from cleanlab.outlier import OutOfDistribution

ood = OutOfDistribution(params={'adjust_pred_probs': False})

ambiguity_scores = ood.fit_score(pred_probs=pred_probs)
```

Learn more about these:

https://docs.cleanlab.ai/stable/tutorials/outliers.html

https://cleanlab.ai/blog/outlier-detection/

https://cleanlab.ai/blog/ood-classifier/

**Comment by jwmueller** [comment]
The algorithms to determine default thresholds in Cleanlab Studio are the same as those in Datalab here:

https://github.com/cleanlab/cleanlab/blob/master/cleanlab/datalab/internal/issue_manager/outlier.py

Cleanlab Studio is built on top of this package.  But for practical purposes, the results will be very different since Cleanlab Studio is doing all the ML for you (in the way that combines optimally with these algorithms).

The best threshold for your use-case will also often differ from the default threshold, so consider what might work best for your specific needs (by examining the outlier_scores) after considering the defaults (and is_outlier booleans).
