### ISSUE TITLE
Object Detection

### ISSUE THREAD

**Issue by zxyx2023** [cleanlab/cleanlab#952]
The process of identifying incorrect labels in object detection relies on the results obtained through k-fold cross-validation. However, when the error rate is high or the dataset is large, how can we ensure that the predictions from k-fold cross-validation are accurate? What if both the annotations and the prediction results are incorrect?

**Comment by jwmueller** [comment]
All label error detection algorithms in Cleanlab are designed to account for imperfect ML models trained on finite data. We are not simply reporting the label issues as those examples where ML model prediction disagrees with the given label, that would produce too many false positives because ML model predictions are imperfect in practice. 

Instead Cleanlab accounts for the expected shortcomings of the ML model and its confidence when determining label issues.

Learn more about how this is done for object detection here:
https://cleanlab.ai/blog/object-detection/

Or learn how it's done for multi-class classification via Confident Learning:
https://l7.curtisnorthcutt.com/confident-learning

That said, the quality of results you get from this library will critically depend on the quality of your ML model. You should try to produce an effective ML model to run this library with, which will help you effectively improve the data, so you can produce an even better ML model (and can iterate this in a virtuous cycle of Data-Centric AI).

If you're not getting the best results or unsure what ML model is best, consider trying Cleanlab Studio which handles all the ML for you automatically:  https://cleanlab.ai/blog/data-centric-ai/

**Comment by zxyx2023** [comment]
The model can be used for rotated bounding box object detection, can it? What modifications are needed for this purpose?

**Comment by jwmueller** [comment]
Currently it's just for standard rectangular bounding box error detection. 

If you find an effective way to apply it to rotating bounding box object detection, we'd love to hear about what you did!
And definitely let us know if you're interested in contributing code for such an extension.
